watcher: fix event handler in unmarshal vip
Nordix/Meridio pull request #118
Opened 2021-11-23 09:28 UTC by mandydydy

change unmarshal to unmarshalStrict to restrict unknown fields

2021-11-23 09:46 UTC, LionelJouin requested changes

2021-11-23 09:46 UTC, LionelJouin commented on pkg/configuration/watcher.go
> +	c.VIPs.Vips, err = reader.UnmarshalVips(configmap.Data[reader.VipsConfigKey])
c.GWs and c.VIPs are nil, so an error will be returned.
to solve it, line 78:
```
c := &OperatorConfig{
	GWs:  &reader.GatewayList{},
	VIPs: &reader.VipList{},
}
```

2021-11-23 11:10 UTC, LionelJouin approved these changes

2021-11-23 14:41 UTC, merged

2021-11-23 15:07 UTC, estinfra reviewed
FOSS Introduction is done. Please check the [logs](https://artifactory.est.tech/artifactory/proj-est-nsm-generic-local/reports/meridio/master/ca9d5a5).

2021-11-24 10:47 UTC, estinfra reviewed
FOSS Introduction is done. Please check the [logs](https://artifactory.est.tech/artifactory/proj-est-nsm-generic-local/reports/meridio/master/ca9d5a5).